# Generated by Django 4.1.2 on 2022-10-15 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='summary',
            field=models.TextField(null=True),
        ),
    ]
