# Generated by Django 4.1.2 on 2022-10-18 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_books_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='user_id',
        ),
    ]
