# Generated by Django 4.1.2 on 2022-10-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
