# Generated by Django 4.1.2 on 2022-10-11 04:24

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('summary', models.CharField(max_length=200, null=True)),
                ('image', models.FileField(null=True, upload_to='')),
                ('description', models.CharField(max_length=200, null=True)),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('content', django_quill.fields.QuillField()),
            ],
        ),
    ]
