# Generated by Django 4.1.2 on 2022-10-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_books_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
